package main

import (
	"fmt"
	"time"

	"example-randbyte/randbyte"
)

func main() {
	generator := randbyte.New(time.Now().UnixNano())

	buf := make([]byte, 16)

	for i := 0; i < 5; i++ {
		n, _ := generator.Read(buf)
		fmt.Printf("Generated bytes: %v size(%d)\n", buf, n)
	}
}
